/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniencuesta;

/**
 *
 * @author the_d
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        eSistema = new javax.swing.JLabel();
        eEspecialidad = new javax.swing.JLabel();
        CBprogramacion = new javax.swing.JCheckBox();
        CBdiseno = new javax.swing.JCheckBox();
        CBadministracion = new javax.swing.JCheckBox();
        Slhoras = new javax.swing.JSlider();
        eHoras = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        bGenerar = new javax.swing.JButton();
        cTshoras = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rBwindows = new javax.swing.JRadioButton();
        rBlinux = new javax.swing.JRadioButton();
        rBmac = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        eSistema.setText("Elige un sistema operativo");

        eEspecialidad.setText("Elige tu especialidad");

        CBprogramacion.setText("Programación");

        CBdiseno.setText("Diseño gráfico");

        CBadministracion.setText("Administración");

        Slhoras.setMaximum(10);
        Slhoras.setValue(0);
        Slhoras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SlhorasStateChanged(evt);
            }
        });

        eHoras.setText("Horas que dedicas en el ordenador");

        bGenerar.setText("Generar");
        bGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerarActionPerformed(evt);
            }
        });

        cTshoras.setEditable(false);
        cTshoras.setBorder(null);
        cTshoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTshorasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBwindows);
        rBwindows.setSelected(true);
        rBwindows.setText("Windows");

        buttonGroup1.add(rBlinux);
        rBlinux.setText("Linux");

        buttonGroup1.add(rBmac);
        rBmac.setText("Mac");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBwindows)
                    .addComponent(rBlinux)
                    .addComponent(rBmac))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBwindows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBlinux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBmac)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(cTshoras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slhoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(bGenerar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBprogramacion)
                            .addComponent(eEspecialidad)
                            .addComponent(CBdiseno)
                            .addComponent(CBadministracion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(eHoras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eSistema)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(eSistema)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eEspecialidad)
                        .addGap(18, 18, 18)
                        .addComponent(CBprogramacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBdiseno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBadministracion)
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eHoras)
                        .addGap(35, 35, 35)
                        .addComponent(Slhoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cTshoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(bGenerar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerarActionPerformed
        String cad="";
        String cad2="";
        
        if(this.rBwindows.isSelected()){
            cad=this.rBwindows.getText();
        }
        if(this.rBlinux.isSelected()){
            cad=this.rBlinux.getText();
        }
        if(this.rBmac.isSelected()){
            cad=this.rBmac.getText();
        }
        
        if(this.CBadministracion.isSelected()){
            cad2 = cad2 +", " + this.CBadministracion.getText();
        }
        if(this.CBprogramacion.isSelected()){
            cad2 = cad2 +", " + this.CBprogramacion.getText();
        }
        if(this.CBdiseno.isSelected()){
            cad2 = cad2 +", " + this.CBdiseno.getText();
        }
        
        if(cad2.equals("")){
            javax.swing.JOptionPane.showMessageDialog(null, "Tu sistema operativo preferido es "+cad+","+"\r\n"+ "no tienes especialidades selecionadas"+"\r\n"+"y el número de horas dedicadas al ordenador son "+Slhoras.getValue(), "Muestra de datos", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Tu sistema operativo preferido es "+cad+","+"\r\n"+ "tus especialidades son "+ cad2 +"\r\n"+"y el número de horas dedicadas al ordenador son "+Slhoras.getValue(), "Muestra de datos", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bGenerarActionPerformed

    private void cTshorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTshorasActionPerformed

    }//GEN-LAST:event_cTshorasActionPerformed

    private void SlhorasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SlhorasStateChanged
           this.cTshoras.setText(String.valueOf(this.Slhoras.getValue()));
    }//GEN-LAST:event_SlhorasStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBadministracion;
    private javax.swing.JCheckBox CBdiseno;
    private javax.swing.JCheckBox CBprogramacion;
    private javax.swing.JSlider Slhoras;
    private javax.swing.JButton bGenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cTshoras;
    private javax.swing.JLabel eEspecialidad;
    private javax.swing.JLabel eHoras;
    private javax.swing.JLabel eSistema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rBlinux;
    private javax.swing.JRadioButton rBmac;
    private javax.swing.JRadioButton rBwindows;
    // End of variables declaration//GEN-END:variables
}
