/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro_usuarios;

import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author the_d
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.lista = new LinkedList<>();
        this.cBcargo.addItem("Analista");
        this.cBcargo.addItem("Programador");
        this.cBcargo.addItem("Diseñador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cTdni = new javax.swing.JTextField();
        cTnombre = new javax.swing.JTextField();
        eDni = new javax.swing.JLabel();
        eNombre = new javax.swing.JLabel();
        cBcargo = new javax.swing.JComboBox<>();
        cSedad = new javax.swing.JSpinner();
        eEdad = new javax.swing.JLabel();
        eCargo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rBsoltero = new javax.swing.JRadioButton();
        rBcasado = new javax.swing.JRadioButton();
        bAnadir = new javax.swing.JButton();
        bVerdni = new javax.swing.JButton();
        bBorrarperson = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eDni.setText("DNI");

        eNombre.setText("Nombre");

        eEdad.setText("Edad");

        eCargo.setText("Cargo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado civil"));

        buttonGroup1.add(rBsoltero);
        rBsoltero.setText("Soltero");

        buttonGroup1.add(rBcasado);
        rBcasado.setText("Casado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBsoltero)
                    .addComponent(rBcasado))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rBsoltero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBcasado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bAnadir.setText("Añadir");
        bAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirActionPerformed(evt);
            }
        });

        bVerdni.setText("Ver DNI seleccionado");
        bVerdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerdniActionPerformed(evt);
            }
        });

        bBorrarperson.setText("Borrar persona");
        bBorrarperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarpersonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Estado", "Edad", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eEdad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSedad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eDni)
                                        .addComponent(eNombre))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cTnombre)
                                        .addComponent(cTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(eCargo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(bAnadir))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addComponent(cBcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(11, 11, 11))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVerdni)
                        .addGap(56, 56, 56)
                        .addComponent(bBorrarperson, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cTdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eDni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNombre))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bVerdni)
                            .addComponent(bBorrarperson)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eEdad)
                                .addComponent(cSedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAnadir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVerdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerdniActionPerformed
       Persona p = this.lista.get(this.jTable1.getSelectedRow());
       Ventana1 v1 = new Ventana1(p);
       v1.setVisible(true);
        System.out.println(p);
    }//GEN-LAST:event_bVerdniActionPerformed

    private void bAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirActionPerformed
        Persona p = new Persona();
        Object filan[] = new Object[5];
        
        if(this.comprobarCampos()){
            if(this.estaDni()){
                javax.swing.JOptionPane.showMessageDialog(null, "El DNI ya se encuentra en la lista", "DNI Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                p.setCargo((String) this.cBcargo.getSelectedItem());
                p.setDni(this.cTdni.getText());
                p.setEdad((int) this.cSedad.getValue());
                if(this.rBcasado.isSelected()){
                    p.setEstado("Casado");
                } else {
                    p.setEstado("Soltero");
                }
                p.setNombre(this.cTnombre.getText());
                
                DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
                filan[0] = p.getDni();
                filan[1] = p.getNombre();
                filan[2] = p.getEstado();
                filan[3] = p.getEdad();
                filan[4] = p.getCargo();
                m.addRow(filan);
                this.jTable1.setModel(m);
                
                this.lista.add(p);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe rellenar todos los datos", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAnadirActionPerformed

    private void bBorrarpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarpersonActionPerformed
        int index = this.jTable1.getSelectedRow();
        this.lista.remove(index);
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        m.removeRow(index);
        this.jTable1.setModel(m);
    }//GEN-LAST:event_bBorrarpersonActionPerformed

    private boolean comprobarCampos(){
        boolean estanDatos = true;
        if(this.eDni.getText().trim().length() <= 0){
            estanDatos = false;
        }
        if(this.cTnombre.getText().trim().length() <= 0){
            estanDatos = false;
        }
        if(!this.rBcasado.isSelected() && !this.rBsoltero.isSelected()){
            estanDatos = false;
        }
        return estanDatos;
    }
    
    private boolean estaDni(){
        boolean esta = false;
        for(Persona p : this.lista){
            if(p.getDni().equals(this.cTdni.getText())){
                esta = true;
            }
        }
        return esta;
    }
    
    /**
     * @param args the command line arguments
     */
    
    LinkedList<Persona> lista;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnadir;
    private javax.swing.JButton bBorrarperson;
    private javax.swing.JButton bVerdni;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cBcargo;
    private javax.swing.JSpinner cSedad;
    private javax.swing.JTextField cTdni;
    private javax.swing.JTextField cTnombre;
    private javax.swing.JLabel eCargo;
    private javax.swing.JLabel eDni;
    private javax.swing.JLabel eEdad;
    private javax.swing.JLabel eNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rBcasado;
    private javax.swing.JRadioButton rBsoltero;
    // End of variables declaration//GEN-END:variables
}
