/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author the_d
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cResult = new javax.swing.JTextField();
        bN7 = new javax.swing.JButton();
        bN4 = new javax.swing.JButton();
        bN1 = new javax.swing.JButton();
        bN8 = new javax.swing.JButton();
        bN5 = new javax.swing.JButton();
        bN2 = new javax.swing.JButton();
        bN3 = new javax.swing.JButton();
        bN6 = new javax.swing.JButton();
        bN9 = new javax.swing.JButton();
        bResult = new javax.swing.JButton();
        bN0 = new javax.swing.JButton();
        bPN = new javax.swing.JButton();
        bSum = new javax.swing.JButton();
        bMult = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        bRes = new javax.swing.JButton();
        bClean = new javax.swing.JButton();
        bCleanE = new javax.swing.JButton();
        bMsum = new javax.swing.JButton();
        bMres = new javax.swing.JButton();
        bMsave = new javax.swing.JButton();
        bMrecov = new javax.swing.JButton();
        bMclean = new javax.swing.JButton();
        bSqrt = new javax.swing.JButton();
        bFact = new javax.swing.JButton();
        bPow = new javax.swing.JButton();
        bSen = new javax.swing.JButton();
        bComa = new javax.swing.JButton();
        bRetro = new javax.swing.JButton();
        bCos = new javax.swing.JButton();
        bTan = new javax.swing.JButton();
        bBi_De = new javax.swing.JButton();
        bDe_Bi = new javax.swing.JButton();
        cMemo = new javax.swing.JTextField();
        bExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cResult.setBackground(new java.awt.Color(204, 255, 255));
        cResult.setForeground(new java.awt.Color(0, 0, 0));

        bN7.setBackground(new java.awt.Color(0, 102, 102));
        bN7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN7.setForeground(new java.awt.Color(255, 255, 255));
        bN7.setText("7");
        bN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN7ActionPerformed(evt);
            }
        });

        bN4.setBackground(new java.awt.Color(0, 102, 102));
        bN4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN4.setForeground(new java.awt.Color(255, 255, 255));
        bN4.setText("4");
        bN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN4ActionPerformed(evt);
            }
        });

        bN1.setBackground(new java.awt.Color(0, 102, 102));
        bN1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN1.setForeground(new java.awt.Color(255, 255, 255));
        bN1.setText("1");
        bN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN1ActionPerformed(evt);
            }
        });

        bN8.setBackground(new java.awt.Color(0, 102, 102));
        bN8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN8.setForeground(new java.awt.Color(255, 255, 255));
        bN8.setText("8");
        bN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN8ActionPerformed(evt);
            }
        });

        bN5.setBackground(new java.awt.Color(0, 102, 102));
        bN5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN5.setForeground(new java.awt.Color(255, 255, 255));
        bN5.setText("5");
        bN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN5ActionPerformed(evt);
            }
        });

        bN2.setBackground(new java.awt.Color(0, 102, 102));
        bN2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN2.setForeground(new java.awt.Color(255, 255, 255));
        bN2.setText("2");
        bN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN2ActionPerformed(evt);
            }
        });

        bN3.setBackground(new java.awt.Color(0, 102, 102));
        bN3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN3.setForeground(new java.awt.Color(255, 255, 255));
        bN3.setText("3");
        bN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN3ActionPerformed(evt);
            }
        });

        bN6.setBackground(new java.awt.Color(0, 102, 102));
        bN6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN6.setForeground(new java.awt.Color(255, 255, 255));
        bN6.setText("6");
        bN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN6ActionPerformed(evt);
            }
        });

        bN9.setBackground(new java.awt.Color(0, 102, 102));
        bN9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN9.setForeground(new java.awt.Color(255, 255, 255));
        bN9.setText("9");
        bN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN9ActionPerformed(evt);
            }
        });

        bResult.setBackground(new java.awt.Color(0, 102, 102));
        bResult.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bResult.setForeground(new java.awt.Color(255, 255, 255));
        bResult.setText("=");
        bResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResultActionPerformed(evt);
            }
        });

        bN0.setBackground(new java.awt.Color(0, 102, 102));
        bN0.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bN0.setForeground(new java.awt.Color(255, 255, 255));
        bN0.setText("0");
        bN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN0ActionPerformed(evt);
            }
        });

        bPN.setBackground(new java.awt.Color(0, 102, 102));
        bPN.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bPN.setForeground(new java.awt.Color(255, 255, 255));
        bPN.setText("+/-");
        bPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPNActionPerformed(evt);
            }
        });

        bSum.setBackground(new java.awt.Color(0, 102, 102));
        bSum.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bSum.setForeground(new java.awt.Color(255, 255, 255));
        bSum.setText("+");
        bSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSumActionPerformed(evt);
            }
        });

        bMult.setBackground(new java.awt.Color(0, 102, 102));
        bMult.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bMult.setForeground(new java.awt.Color(255, 255, 255));
        bMult.setText("×");
        bMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultActionPerformed(evt);
            }
        });

        bDiv.setBackground(new java.awt.Color(0, 102, 102));
        bDiv.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bDiv.setForeground(new java.awt.Color(255, 255, 255));
        bDiv.setText("÷");
        bDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivActionPerformed(evt);
            }
        });

        bRes.setBackground(new java.awt.Color(0, 102, 102));
        bRes.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bRes.setForeground(new java.awt.Color(255, 255, 255));
        bRes.setText("-");
        bRes.setMaximumSize(new java.awt.Dimension(40, 25));
        bRes.setMinimumSize(new java.awt.Dimension(40, 25));
        bRes.setPreferredSize(new java.awt.Dimension(40, 25));
        bRes.setRequestFocusEnabled(false);
        bRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResActionPerformed(evt);
            }
        });

        bClean.setBackground(new java.awt.Color(0, 102, 102));
        bClean.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bClean.setForeground(new java.awt.Color(255, 255, 255));
        bClean.setText("C");
        bClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCleanActionPerformed(evt);
            }
        });

        bCleanE.setBackground(new java.awt.Color(0, 102, 102));
        bCleanE.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bCleanE.setForeground(new java.awt.Color(255, 255, 255));
        bCleanE.setText("CE");
        bCleanE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCleanEActionPerformed(evt);
            }
        });

        bMsum.setBackground(new java.awt.Color(0, 102, 102));
        bMsum.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bMsum.setForeground(new java.awt.Color(255, 255, 255));
        bMsum.setText("M+");
        bMsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMsumActionPerformed(evt);
            }
        });

        bMres.setBackground(new java.awt.Color(0, 102, 102));
        bMres.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bMres.setForeground(new java.awt.Color(255, 255, 255));
        bMres.setText("M-");
        bMres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMresActionPerformed(evt);
            }
        });

        bMsave.setBackground(new java.awt.Color(0, 102, 102));
        bMsave.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bMsave.setForeground(new java.awt.Color(255, 255, 255));
        bMsave.setText("MS");
        bMsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMsaveActionPerformed(evt);
            }
        });

        bMrecov.setBackground(new java.awt.Color(0, 102, 102));
        bMrecov.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bMrecov.setForeground(new java.awt.Color(255, 255, 255));
        bMrecov.setText("MR");
        bMrecov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMrecovActionPerformed(evt);
            }
        });

        bMclean.setBackground(new java.awt.Color(0, 102, 102));
        bMclean.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bMclean.setForeground(new java.awt.Color(255, 255, 255));
        bMclean.setText("MC");
        bMclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMcleanActionPerformed(evt);
            }
        });

        bSqrt.setBackground(new java.awt.Color(0, 102, 102));
        bSqrt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bSqrt.setForeground(new java.awt.Color(255, 255, 255));
        bSqrt.setText("√");
        bSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSqrtActionPerformed(evt);
            }
        });

        bFact.setBackground(new java.awt.Color(0, 102, 102));
        bFact.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bFact.setForeground(new java.awt.Color(255, 255, 255));
        bFact.setText("n!");
        bFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFactActionPerformed(evt);
            }
        });

        bPow.setBackground(new java.awt.Color(0, 102, 102));
        bPow.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bPow.setForeground(new java.awt.Color(255, 255, 255));
        bPow.setText("pow");
        bPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPowActionPerformed(evt);
            }
        });

        bSen.setBackground(new java.awt.Color(0, 102, 102));
        bSen.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bSen.setForeground(new java.awt.Color(255, 255, 255));
        bSen.setText("sen");
        bSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSenActionPerformed(evt);
            }
        });

        bComa.setBackground(new java.awt.Color(0, 102, 102));
        bComa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bComa.setForeground(new java.awt.Color(255, 255, 255));
        bComa.setText(",");
        bComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComaActionPerformed(evt);
            }
        });

        bRetro.setBackground(new java.awt.Color(0, 102, 102));
        bRetro.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bRetro.setForeground(new java.awt.Color(255, 255, 255));
        bRetro.setText("<--");
        bRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetroActionPerformed(evt);
            }
        });

        bCos.setBackground(new java.awt.Color(0, 102, 102));
        bCos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bCos.setForeground(new java.awt.Color(255, 255, 255));
        bCos.setText("cos");
        bCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCosActionPerformed(evt);
            }
        });

        bTan.setBackground(new java.awt.Color(0, 102, 102));
        bTan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bTan.setForeground(new java.awt.Color(255, 255, 255));
        bTan.setText("tan");
        bTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTanActionPerformed(evt);
            }
        });

        bBi_De.setBackground(new java.awt.Color(0, 102, 102));
        bBi_De.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bBi_De.setForeground(new java.awt.Color(255, 255, 255));
        bBi_De.setText("Bin-->Dec");
        bBi_De.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBi_DeActionPerformed(evt);
            }
        });

        bDe_Bi.setBackground(new java.awt.Color(0, 102, 102));
        bDe_Bi.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bDe_Bi.setForeground(new java.awt.Color(255, 255, 255));
        bDe_Bi.setText("Dec-->Bin");
        bDe_Bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDe_BiActionPerformed(evt);
            }
        });

        cMemo.setBackground(new java.awt.Color(0, 51, 102));
        cMemo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cMemo.setForeground(new java.awt.Color(255, 102, 0));
        cMemo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bResult, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(77, 77, 77)
                                    .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bMsave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bMrecov, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bMclean, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bMsum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bMres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bBi_De, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bDe_Bi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bPN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bN0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bComa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bN1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(bN4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(bN7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bN2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                                    .addComponent(bN5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bN6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                                    .addComponent(bN3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bN8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bN9, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bMult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bRes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bFact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bClean, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCleanE, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bPow, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bSen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(cMemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(cResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMsave)
                    .addComponent(bMrecov)
                    .addComponent(bMclean)
                    .addComponent(bMsum)
                    .addComponent(bMres)
                    .addComponent(bRetro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bN7)
                            .addComponent(bN9)
                            .addComponent(bRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bN8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bN4)
                            .addComponent(bN5)
                            .addComponent(bN6)
                            .addComponent(bSum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bN1)
                            .addComponent(bN2)
                            .addComponent(bN3)
                            .addComponent(bMult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bN0)
                            .addComponent(bPN)
                            .addComponent(bDiv)
                            .addComponent(bComa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSqrt)
                            .addComponent(bCos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bFact)
                            .addComponent(bTan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bPow)
                            .addComponent(bClean))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSen)
                            .addComponent(bCleanE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bResult)
                    .addComponent(bBi_De)
                    .addComponent(bDe_Bi))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCleanEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCleanEActionPerformed
        number1 = "";
        number2 = "";
        result = "";
        operacion = ' ';
        memoria = "";

        cResult.setText("");
        cMemo.setText("");
    }//GEN-LAST:event_bCleanEActionPerformed

    private void bPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPNActionPerformed
        int num;

        num = Integer.parseInt(cResult.getText());

        if (num > 0 || num < 0) {
            num = num * -1;
        }

        cResult.setText(String.valueOf(num));
    }//GEN-LAST:event_bPNActionPerformed

    private void bN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN7ActionPerformed

        cResult.setText(cResult.getText() + "7");
    }//GEN-LAST:event_bN7ActionPerformed

    private void bN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN8ActionPerformed

        cResult.setText(cResult.getText() + "8");
    }//GEN-LAST:event_bN8ActionPerformed

    private void bResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResultActionPerformed
        int n1, n2, res;
        float num, resf;

        try {

            if (!cResult.getText().equals("")) {
                number2 = cResult.getText();
            }

            switch (operacion) {
                case '+':
                    n1 = Integer.parseInt(number1);
                    n2 = Integer.parseInt(number2);

                    res = n1 + n2;

                    result = String.valueOf(res);

                    cResult.setText(result);
                    break;
                case '-':
                    n1 = Integer.parseInt(number1);
                    n2 = Integer.parseInt(number2);

                    res = n1 - n2;

                    result = String.valueOf(res);

                    cResult.setText(result);
                    break;
                case '*':
                    n1 = Integer.parseInt(number1);
                    n2 = Integer.parseInt(number2);

                    res = n1 * n2;

                    result = String.valueOf(res);

                    cResult.setText(result);
                    break;
                case '/':
                    n1 = Integer.parseInt(number1);
                    n2 = Integer.parseInt(number2);

                    if (n2 != 0) {
                        res = n1 / n2;

                        result = String.valueOf(res);

                        cResult.setText(result);
                    } else {
                        cResult.setText("No se puede dividir por cero");
                    }
                    break;
                default:
                    throw new AssertionError();
            }
        } catch (ArithmeticException ex) {
            cResult.setText("No se puede por cero");
        } catch (NumberFormatException ex) {
            cResult.setText("Introduce un numero primero");
        } catch (NullPointerException ex) {
            cResult.setText("Introduce un segundo numero primero");
        }
    }//GEN-LAST:event_bResultActionPerformed

    private void bN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN9ActionPerformed

        cResult.setText(cResult.getText() + "9");
    }//GEN-LAST:event_bN9ActionPerformed

    private void bN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN4ActionPerformed

        cResult.setText(cResult.getText() + "4");
    }//GEN-LAST:event_bN4ActionPerformed

    private void bN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN5ActionPerformed

        cResult.setText(cResult.getText() + "5");
    }//GEN-LAST:event_bN5ActionPerformed

    private void bN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN6ActionPerformed

        cResult.setText(cResult.getText() + "6");
    }//GEN-LAST:event_bN6ActionPerformed

    private void bN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN1ActionPerformed

        cResult.setText(cResult.getText() + "1");
    }//GEN-LAST:event_bN1ActionPerformed

    private void bN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN2ActionPerformed

        cResult.setText(cResult.getText() + "2");
    }//GEN-LAST:event_bN2ActionPerformed

    private void bN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN3ActionPerformed

        cResult.setText(cResult.getText() + "3");
    }//GEN-LAST:event_bN3ActionPerformed

    private void bN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN0ActionPerformed

        cResult.setText(cResult.getText() + "0");
    }//GEN-LAST:event_bN0ActionPerformed

    private void bResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResActionPerformed

        if (!cResult.getText().equals("")) {
            number1 = cResult.getText();
            operacion = '-';
            cResult.setText("");
        }
    }//GEN-LAST:event_bResActionPerformed

    private void bSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSumActionPerformed

        if (!cResult.getText().equals("")) {
            number1 = cResult.getText();
            operacion = '+';
            cResult.setText("");
        }
    }//GEN-LAST:event_bSumActionPerformed

    private void bMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultActionPerformed

        if (!cResult.getText().equals("")) {
            number1 = cResult.getText();
            operacion = '*';
            cResult.setText("");
        }
    }//GEN-LAST:event_bMultActionPerformed

    private void bDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivActionPerformed

        if (!cResult.getText().equals("")) {
            number1 = cResult.getText();
            operacion = '/';
            cResult.setText("");
        }
    }//GEN-LAST:event_bDivActionPerformed

    private void bCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCleanActionPerformed
        cResult.setText("");
    }//GEN-LAST:event_bCleanActionPerformed

    private void bMsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMsumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMsumActionPerformed

    private void bMresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMresActionPerformed

    private void bMsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMsaveActionPerformed
        memoria = cResult.getText();

        cMemo.setText(memoria);
        cResult.setText("");
    }//GEN-LAST:event_bMsaveActionPerformed

    private void bMrecovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMrecovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMrecovActionPerformed

    private void bMcleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMcleanActionPerformed
        memoria = "";

        cMemo.setText("");
    }//GEN-LAST:event_bMcleanActionPerformed

    private void bSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSqrtActionPerformed
        float num, resf;
        if (!cResult.getText().equals("")) {
            number1 = cResult.getText();
            num = Float.parseFloat(number1);

            resf = (float) (Math.sqrt(num));

            result = String.valueOf(resf);

            cResult.setText(result);
        }
    }//GEN-LAST:event_bSqrtActionPerformed

    private void bFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFactActionPerformed
        int num, res;
        if (!cResult.getText().equals("")) {
            number1 = cResult.getText();
            num = Integer.parseInt(number1);

            res = num;

            for (int i = num - 1; i > 0; i--) {
                res = res * i;
            }

            result = String.valueOf(res);

            cResult.setText(result);
        }
    }//GEN-LAST:event_bFactActionPerformed

    private void bPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPowActionPerformed

    private void bSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSenActionPerformed

    private void bComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComaActionPerformed
        String cad;

        cad = cResult.getText();

        if (cad.length() <= 0) {
            cResult.setText("0.");
        } else {
            if (!existepunto(cResult.getText())) {
                cResult.setText(cResult.getText() + ".");
            }
        }
    }//GEN-LAST:event_bComaActionPerformed

    private void bRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetroActionPerformed
        String cad;
        cad = cResult.getText();

        if (cad.length() > 0) {
            cad = cad.substring(0, cad.length() - 1);
            cResult.setText(cad);
        }

        cResult.setText(cad);
    }//GEN-LAST:event_bRetroActionPerformed

    private void bCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCosActionPerformed

    private void bTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTanActionPerformed

    private void bBi_DeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBi_DeActionPerformed
        int n_binario;
        int n_decimal;
        boolean esBinario;

        if (!cResult.getText().equals("")) {

            try {
                number1 = cResult.getText();
                cResult.setText("");
                esBinario = esbinario(number1);
                if (esBinario) {
                    number1 = convertirADecimal();
                    cResult.setText(number1);
                }
            } catch (Exception e) {
                if (!esbinario(number1)) {
                    javax.swing.JOptionPane.showInternalMessageDialog(null, "No es un número binario", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } else {
            cResult.setText("No hay nada en la caja");
        }
    }//GEN-LAST:event_bBi_DeActionPerformed

    private void bDe_BiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDe_BiActionPerformed

        boolean esDecimal;

        if (!cResult.getText().equals("")) {

            try {
                number1 = cResult.getText();
                cResult.setText("");
                esDecimal = esdecimal(number1);
                if (esDecimal) {
                    number1 = convertirABinario();
                    cResult.setText(number1);
                }
            } catch (Exception e) {
                if (!esbinario(number1)) {
                    javax.swing.JOptionPane.showInternalMessageDialog(null, "No es un número binario", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } else {
            cResult.setText("No hay nada en la caja");
        }
    }//GEN-LAST:event_bDe_BiActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    public static boolean existepunto(String cad) {
        boolean existe = false;

        for (int i = 0; i < cad.length(); i++) {
            if (cad.substring(i, i + 1).equals(".")) {
                existe = true;
            }
        }
        return existe;
    }

    public static boolean esbinario(String cad) {
        boolean isBinary = true;

        for (int i = 0; i < cad.length(); i++) {
            if (cad.charAt(i) != '0' && cad.charAt(i) != '1') {
                isBinary = false;
            }
        }
        return isBinary;
    }
    
    public static boolean esdecimal(String cad) {
        boolean isDecimal = true;
        
        return isDecimal;
    }

    private String convertirABinario(){
       String n="";
        
        return n;
    }
    
    private String convertirADecimal() {
        int n1;
        int dec = 0;
        int ult = 0;
        int exp = 0;
        int n2;
        String n;
        n1 = Integer.parseInt(number1);

        n2 = n1;

        while (n2 != 0) {
            ult = n2 % 10;
            n2 = n2 / 10;
            System.out.println(n2);
            dec = dec + ult * (int) Math.pow(2, exp);
            exp++;
        }
        n = String.valueOf(dec);

        return n;
    }

    private String memoria;
    private String number1;
    private String number2;
    private String result;
    private char operacion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBi_De;
    private javax.swing.JButton bClean;
    private javax.swing.JButton bCleanE;
    private javax.swing.JButton bComa;
    private javax.swing.JButton bCos;
    private javax.swing.JButton bDe_Bi;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bFact;
    private javax.swing.JButton bMclean;
    private javax.swing.JButton bMrecov;
    private javax.swing.JButton bMres;
    private javax.swing.JButton bMsave;
    private javax.swing.JButton bMsum;
    private javax.swing.JButton bMult;
    private javax.swing.JButton bN0;
    private javax.swing.JButton bN1;
    private javax.swing.JButton bN2;
    private javax.swing.JButton bN3;
    private javax.swing.JButton bN4;
    private javax.swing.JButton bN5;
    private javax.swing.JButton bN6;
    private javax.swing.JButton bN7;
    private javax.swing.JButton bN8;
    private javax.swing.JButton bN9;
    private javax.swing.JButton bPN;
    private javax.swing.JButton bPow;
    private javax.swing.JButton bRes;
    private javax.swing.JButton bResult;
    private javax.swing.JButton bRetro;
    private javax.swing.JButton bSen;
    private javax.swing.JButton bSqrt;
    private javax.swing.JButton bSum;
    private javax.swing.JButton bTan;
    private javax.swing.JTextField cMemo;
    private javax.swing.JTextField cResult;
    // End of variables declaration//GEN-END:variables
}
